# -*- coding: utf-8 -*-
"""파이썬입문.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aHuwcx7W_pFwmoDFt31BxyyRA0YUD61K
"""

print('안녕하세요', end='')
print('저는 홍길동입니다.')

# 설명을 씀, 컨트롤 +/,comment, 주석
# 입력:데이터를 가지고 와야함.
# 처리:적절한 처리
# 출력:처리한 결과를 내보는 일(모니터, 파일, db저장, 네트워크 전송)

name = input('입력을 입력하세요>>') #간단한 처리(기호를 씀): 연산 =>연산자

print(name)

소속 =input('소속을 입력하세요>>')
이름 =input('이름을 입력하세요>>')
나이 =input('나이를 입력하세요>>')

print(소속)
print(이름)
print(나이)

location='신촌'

number = 2

height= 195.5

food_lunch = True

age2= input('나이 입력>>')#100 
#컴퓨터에서 입력한 데이터는 타입을 무조건 스트링으로 인식!
#스트링을 정수로 바꾸어스는(강제 캐스팅) 결정은 프로그래머가 한다.
print('내년 나이는',int(age2)+1)

#두 수를 입력을 받아서, 사칙연산을 해보세세요.
number1=input('수1 입력>>')
number2=input('수2 입력>>')
print('두 수의 합은',int(number1)+int(number2))
print('두 수의 차이는',int(number1)-int(number2))
print('두 수의 곱은',int(number1)*int(number2))
print('두 수를 나누면',int(number1)/int(number2))

n1 = int(input('숫자1>>'))
n2 = int(input('숫자2>>'))

print('두 수의 합은 ',n1+n2)#산술 연산자(더하기 연산)
print('두 수의 합은 ',n1-n2)
print('두 수의 합은 ',n1+n2)
print('두 수의 합은 ',n1+n2)

me='커피'
me2='우유'
print(me+me2)#문자열로 결합시켜라(결합연사자)

price = 1000

print(me +'가격은' + str(price) + '원')

cost=int(input('커피값 입력:'))#input값을 받아서 갖고 오는 것이 input의 기능
number=int(input('커피 인원수:'))
sum=cost*number#변수(저장공간, 저장공간이름=>변수명)

if sum >= 20000: #True일때만!, 비교할게 잇어야 함
  print('20000원 이상입니다.')
  print(sum - 2000, '원 결제하세요')
else: #False인 모든 상황!
  print('20000원 이상입니다.')
  print(sum, '원 결제하세요.')

deposit=int(input('1년 만기 정기 예금을 얼마나 예치하시겠습니까?'))
principal=deposit*0.1
principal=int(principal)
print('원금이',deposit,'원이시군요.!')
print('이자는', principal,'원입니다.')
print('원리합계는', deposit + principal, '원입니다.' )

english=int(input('영어 점수 입력:'))
math=int(input('수학 점수 입력:'))
korean=int(input('국어 점수 입력:'))
sum=english+math+korean
average=(english+math+korean)/3
print('세 과목의 합은', sum, '점')
print('세 과목의 평균은',average, '점')

time=int(input('지금은 몇시입니까?'))
if time>=12:
  print(time,'보다 작으면 점심 전입니다. 맛있게 드세요.!', end='')
  print('아니면 점심후입니다')

id=input('원래 가입한 아이디는:')
login=input('로그인 할 id를 입력>>')
if id==login:
  print('로그인 되었습니다.')

  login=input('로그인 할 id를 입력>>')
if id!=login:
  print('로그인 되지 않았습니다.')

s_cost=1000
s_number=3
b_cost=2500
b_number=4
real_cost=(s_cost*s_number+b_cost*b_number)
sale=int(real_cost*0.9)
print('교보문고에 가서',s_cost,'원짜리 스티커 장과', s_number,'원짜리 책갈피를 개 샀습니다. 우수회원 할인으로 10%할인을 받았습니다.')
print('내가 낸 금액은 얼마일까요?',sale,'원')

