# -*- coding: utf-8 -*-
"""파이썬제어문.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZIdNHUcwdJ8Hk9AADO79PAUPiDxeHV_U
"""

food=input('먹고 싶은 음식을 입력하세요.>>')
print('당신이 입력한 먹고 싶은 음식은', food)

if food =='우동':
  print('우산을 들고 간다')
  print('돈 들고 간다.')
  print('우동집으로 간다')
elif food=='짜장면':
  print('중국집으로 간다.')
elif food=='라면':
  print('분식집으로 간다.')
else:# else 뒤에는 조건을 쓰지 않는다.
  print('집에서 먹는다.')  #pass

start = 0 #시작값
while start < 10: #True, 조건식
   print(start, '> 내가 반복')
   start = start +1

for x in range(0, 10, 2):#0~9, 기본값이 1식 증가! 
  print(x,'나도 반복')

time=int(input('현재 시각'))

if time <= 11:
  print('굿모닝')
elif 11 <time<= 15: # 11< 안써도 됨
  print('굿애프터눈')
elif 15 <time<= 20:
  print('굿이브닝')
else:
  print('굿나잇')

month=int(input('이번달은'))

if 3<=month<6:
   print('봄')
elif 6<=month<9:
  print('여름')
elif 9<=month<12: #위에서 걸리면break, cpu처리 여기서 끝
  print('가을')
else:
  print('겨울')

